// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/Quiz6.gold"
import gold.structures.automaton.*;
import gold.structures.set.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Quiz6 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=8;
      System.out.println($message(new Object[]{"Hello World"}));
      $line=10;
      Object a=$fix(GCollections.asSet(0,1));
      $line=11;
      Object states=$fix($opCartsY(new Object[]{a,$opIntvlY(0,9)}));
      $line=13;
      Object Q=$fix($opUnionY(states,GCollections.asSet('f')));
      $line=15;
      Object A=$fix($opUnionY($opIntvlY('0','9'),GCollections.asSet('$')));
      $line=16;
      Object O=$fix(A);
      $line=18;
      Object q_0=$fix(GCollections.asList(0,0));
      $line=19;
      Object F=$fix(GCollections.asSet('f'));
      $line=23;
      Object M=$fix($invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,A,O,q_0,F,new GMethod(Quiz6.class,"delta"),new GMethod(Quiz6.class,"g"),new GMethod(Quiz6.class,"h")}));
      $line=24;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,M));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Quiz6.class,"main",$line);
    }
  }
  public static Object g(java.lang.Iterable $v1, Object d) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v2=GCollections.unmodifiableCollection($v1).iterator();
      Object c=$v2.next();
      Object s=$v2.next();
      $line=29;
      $result="";
      if (true) break $try;
      $line=30;
      $rethrow(new RuntimeException("The function \"g(\u27E8c,s\u27E9:java.lang.Iterable,d:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Quiz6.class,"g",$line);
    }
    return $result;
  }
  public static Object delta(java.lang.Iterable $v3, Object d) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v4=GCollections.unmodifiableCollection($v3).iterator();
      Object c=$v4.next();
      Object s=$v4.next();
      $line=34;
      Object A=$fix($opIntvlY(1,3));
      $line=37;
      if ($opEqualY(d,'$')) {
        $line=37;
        $result='f';
        if (true) break $try;
      }
      else {
        $line=39;
        Object suma=$fix($opAdditY($opAdditY(s,d),c));
        $line=40;
        Object intDiv=$fix(0);
        $line=42;
        if ($bool($opGreaqY(suma,10))) {
          $line=42;
          intDiv=$fix(1);
        }
        $line=44;
        $result=GCollections.asList(intDiv,d);
        if (true) break $try;
      }
      $line=46;
      $rethrow(new RuntimeException("The function \"delta(\u27E8c,s\u27E9:java.lang.Iterable,d:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Quiz6.class,"delta",$line);
    }
    return $result;
  }
  public static Object h(java.lang.Iterable $v5, Object d) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v6=GCollections.unmodifiableCollection($v5).iterator();
      Object c=$v6.next();
      Object s=$v6.next();
      $line=50;
      Object A=$fix($opIntvlY('1','3'));
      $line=51;
      Object signs=$fix(GCollections.asSet('+','-'));
      $line=54;
      if ($opEqualY(d,'$')) {
        $line=54;
        $result='$';
        if (true) break $try;
      }
      else {
        $line=55;
        $result=$opModulY($opAdditY($opAdditY(s,c),d),10);
        if (true) break $try;
      }
      $line=57;
      $rethrow(new RuntimeException("The function \"h(\u27E8c,s\u27E9:java.lang.Iterable,d:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Quiz6.class,"h",$line);
    }
    return $result;
  }
}
