/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOVE = 4;
  /** RegularExpression Id. */
  int DROP = 5;
  /** RegularExpression Id. */
  int FREE = 6;
  /** RegularExpression Id. */
  int PICK = 7;
  /** RegularExpression Id. */
  int POP = 8;
  /** RegularExpression Id. */
  int TURNRIGHT = 9;
  /** RegularExpression Id. */
  int TURNLEFT = 10;
  /** RegularExpression Id. */
  int LOOK = 11;
  /** RegularExpression Id. */
  int CHECK = 12;
  /** RegularExpression Id. */
  int ROTATE = 13;
  /** RegularExpression Id. */
  int NOP = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int INT = 16;
  /** RegularExpression Id. */
  int PIF = 17;
  /** RegularExpression Id. */
  int BLOP = 18;
  /** RegularExpression Id. */
  int NOBLOP = 19;
  /** RegularExpression Id. */
  int BLOCK = 20;
  /** RegularExpression Id. */
  int DEFINE = 21;
  /** RegularExpression Id. */
  int REP = 22;
  /** RegularExpression Id. */
  int TO = 23;
  /** RegularExpression Id. */
  int OUTP = 24;
  /** RegularExpression Id. */
  int END = 25;
  /** RegularExpression Id. */
  int LETTER = 26;
  /** RegularExpression Id. */
  int NOMB = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"MOVE\"",
    "\"DROP\"",
    "\"FREE\"",
    "\"PICK\"",
    "\"POP\"",
    "\"RIGHT\"",
    "\"LEFT\"",
    "\"LOOK\"",
    "\"CHECK\"",
    "\"ROTATE\"",
    "\"NOP\"",
    "<DIGIT>",
    "<INT>",
    "\"IF\"",
    "\"BLOCKEDP\"",
    "\"!BLOCKEDP\"",
    "\"BLOCK\"",
    "\"DEFINE\"",
    "\"REPEAT\"",
    "\"TO\"",
    "\"OUTPUT\"",
    "\"END\"",
    "<LETTER>",
    "<NOMB>",
    "\":\"",
    "\"\\n\"",
    "\"N\"",
    "\"W\"",
    "\"E\"",
    "\"S\"",
    "\"C\"",
    "\"B\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
  };

}
