// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/PQ4JuanManuel.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class PQ4JuanManuel {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,PQ4JuanManuel.createAutomaton()));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PQ4JuanManuel.class,"main",$line);
    }
  }
  public static IPushdownAutomaton createAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=8;
      Object \u03A3=$fix(GCollections.asSet('2','5','3','\u00D7','q','r','x','=','+','\u00F7'));
      $line=10;
      Object Q=$fix($opUnionY(GCollections.asSet(1,2),$opCartsY(new Object[]{GCollections.asSet(3,4,5,6,7),GCollections.asSet('2','5','3')})));
      $line=11;
      Object \u0393=$fix(GCollections.asSet('x','q'));
      $line=12;
      Object q_0=$fix(1);
      $line=13;
      Object F=$fix($opCartsY(new Object[]{GCollections.asSet(6,7),GCollections.asSet('2','5','3')}));
      $line=14;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=15;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,1,$cast(java.lang.String.class,'x')),new Object[]{"x"});
      $line=16;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,'\u00F7')),new Object[]{});
      $line=17;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,GCollections.asList(3,'2'),$cast(java.lang.String.class,'2')),new Object[]{});
      $line=18;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,GCollections.asList(3,'3'),$cast(java.lang.String.class,'3')),new Object[]{});
      $line=19;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,GCollections.asList(3,'5'),$cast(java.lang.String.class,'5')),new Object[]{});
      $line=21;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(3,'2'),GCollections.asList(4,'2'),$cast(java.lang.String.class,'=')),new Object[]{});
      $line=22;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(3,'3'),GCollections.asList(4,'3'),$cast(java.lang.String.class,'=')),new Object[]{});
      $line=23;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(3,'5'),GCollections.asList(4,'5'),$cast(java.lang.String.class,'=')),new Object[]{});
      $line=25;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(4,'2'),GCollections.asList(4,'2'),$cast(java.lang.String.class,'q')),new Object[]{"xx"});
      $line=26;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(4,'3'),GCollections.asList(4,'3'),$cast(java.lang.String.class,'q')),new Object[]{"xxx"});
      $line=27;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(4,'5'),GCollections.asList(4,'5'),$cast(java.lang.String.class,'q')),new Object[]{"xxxxx"});
      $line=29;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(4,'2'),GCollections.asList(5,'2'),$cast(java.lang.String.class,'\u00D7')),new Object[]{});
      $line=30;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(5,'2'),GCollections.asList(6,'2'),$cast(java.lang.String.class,'2')),new Object[]{});
      $line=31;
      $invokeMethod("skip",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(6,'2'),GCollections.asList(7,'2'),$cast(java.lang.String.class,'+')),new Object[]{"x"});
      $line=32;
      $invokeMethod("skip",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(7,'2'),GCollections.asList(7,'2'),$cast(java.lang.String.class,'r')),new Object[]{"x"});
      $line=34;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(4,'3'),GCollections.asList(5,'3'),$cast(java.lang.String.class,'\u00D7')),new Object[]{});
      $line=35;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(5,'3'),GCollections.asList(6,'3'),$cast(java.lang.String.class,'3')),new Object[]{});
      $line=36;
      $invokeMethod("skip",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(6,'3'),GCollections.asList(7,'3'),$cast(java.lang.String.class,'+')),new Object[]{"x"});
      $line=37;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(7,'3'),GCollections.asList(7,'3'),$cast(java.lang.String.class,'r')),new Object[]{"x"});
      $line=39;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(4,'5'),GCollections.asList(5,'5'),$cast(java.lang.String.class,'\u00D7')),new Object[]{});
      $line=40;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(5,'5'),GCollections.asList(6,'5'),$cast(java.lang.String.class,'5')),new Object[]{});
      $line=41;
      $invokeMethod("skip",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(6,'5'),GCollections.asList(7,'5'),$cast(java.lang.String.class,'+')),new Object[]{"x"});
      $line=42;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(GCollections.asList(7,'5'),GCollections.asList(7,'5'),$cast(java.lang.String.class,'r')),new Object[]{"x"});
      $line=44;
      $result=M;
      if (true) break $try;
      $line=45;
      $rethrow(new RuntimeException("The function \"createAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PQ4JuanManuel.class,"createAutomaton",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
}
