// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/PQ3.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class PQ3 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=6;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=7;
      Object coder=$fix(PQ3.createCoder());
      $line=8;
      Object deCoder=$fix(PQ3.createDecoder());
      $line=13;
      Utilities.testCodeDecode($cast(gold.structures.automaton.ITransducer.class,coder),$cast(gold.structures.automaton.ITransducer.class,deCoder));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PQ3.class,"main",$line);
    }
  }
  public static ITransducer createCoder() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=21;
      Object Bits=$fix(GCollections.asSet(0,1));
      $line=22;
      Object Q=$fix($opCartsY(new Object[]{Bits,Bits,Bits}));
      $line=24;
      Object In=$fix(GCollections.asSet('a','b','c'));
      $line=25;
      Object Out=$fix($opIntvlY('0','7'));
      $line=26;
      Object q_0=$fix(GCollections.asList(0,0,0));
      $line=27;
      Object F=$fix(Q);
      $line=29;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,In,Out,q_0,F,new GMethod(PQ3.class,"\u03B4"),new GMethod(PQ3.class,"g"),new GMethod(PQ3.class,"h")});
      if (true) break $try;
      $line=30;
      $rethrow(new RuntimeException("The function \"createCoder()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PQ3.class,"createCoder",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(java.lang.Iterable $v1, Object letter) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v2=GCollections.unmodifiableCollection($v1).iterator();
      Object ba=$v2.next();
      Object bb=$v2.next();
      Object bc=$v2.next();
      $line=33;
      if ($opEqualY(letter,'a')) {
        $line=33;
        $result=GCollections.asList($opModulY($opAdditY(ba,1),2),bb,bc);
        if (true) break $try;
      }
      else {
        $line=35;
        if ($opEqualY(letter,'b')) {
          $line=35;
          $result=GCollections.asList(ba,$opModulY($opAdditY(bb,1),2),bc);
          if (true) break $try;
        }
        else {
          $line=37;
          $result=GCollections.asList(ba,bb,$opModulY($opAdditY(bc,1),2));
          if (true) break $try;
        }
      }
      $line=41;
      $rethrow(new RuntimeException("The function \"\u03B4(\u27E8ba,bb,bc\u27E9:java.lang.Iterable,letter:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PQ3.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(java.lang.Iterable $v3) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v4=GCollections.unmodifiableCollection($v3).iterator();
      Object ba=$v4.next();
      Object bb=$v4.next();
      Object bc=$v4.next();
      $line=44;
      $result=$opAdditY($opAdditY($opMultpY($opMultpY(ba,2),2),$opMultpY(bb,2)),bc);
      if (true) break $try;
      $line=45;
      $rethrow(new RuntimeException("The function \"g(\u27E8ba,bb,bc\u27E9:java.lang.Iterable)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PQ3.class,"g",$line);
    }
    return $result;
  }
  public static Object h(java.lang.Iterable $v5, Object letter) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v6=GCollections.unmodifiableCollection($v5).iterator();
      Object ba=$v6.next();
      Object bb=$v6.next();
      Object bc=$v6.next();
      $line=48;
      $result="";
      if (true) break $try;
      $line=49;
      $rethrow(new RuntimeException("The function \"h(\u27E8ba,bb,bc\u27E9:java.lang.Iterable,letter:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PQ3.class,"h",$line);
    }
    return $result;
  }
  public static ITransducer createDecoder() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=56;
      Object Bits=$fix(GCollections.asSet(0,1));
      $line=57;
      Object Q=$fix($opCartsY(new Object[]{Bits,Bits,Bits}));
      $line=59;
      Object In=$fix($opIntvlY('0','7'));
      $line=60;
      Object Out=$fix(GCollections.asSet('a','b','c'));
      $line=62;
      Object q_0=$fix(GCollections.asList(0,0,0));
      $line=63;
      Object F=$fix(Q);
      $line=65;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,In,Out,q_0,F,new GMethod(PQ3.class,"\u03B41"),new GMethod(PQ3.class,"g1"),new GMethod(PQ3.class,"h1")});
      if (true) break $try;
      $line=66;
      $rethrow(new RuntimeException("The function \"createDecoder()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PQ3.class,"createDecoder",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B41(java.lang.Iterable $v7, Object number) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v8=GCollections.unmodifiableCollection($v7).iterator();
      Object ba=$v8.next();
      Object bb=$v8.next();
      Object bc=$v8.next();
      $line=70;
      if ($opEqualY(number,'0')) {
        $line=70;
        $result=GCollections.asList(0,0,0);
        if (true) break $try;
      }
      else {
        $line=71;
        if ($opEqualY(number,'1')) {
          $line=71;
          $result=GCollections.asList(0,0,1);
          if (true) break $try;
        }
        else {
          $line=72;
          if ($opEqualY(number,'2')) {
            $line=72;
            $result=GCollections.asList(0,1,0);
            if (true) break $try;
          }
          else {
            $line=73;
            if ($opEqualY(number,'3')) {
              $line=73;
              $result=GCollections.asList(0,1,1);
              if (true) break $try;
            }
            else {
              $line=74;
              if ($opEqualY(number,'4')) {
                $line=74;
                $result=GCollections.asList(1,0,0);
                if (true) break $try;
              }
              else {
                $line=75;
                if ($opEqualY(number,'5')) {
                  $line=75;
                  $result=GCollections.asList(1,0,1);
                  if (true) break $try;
                }
                else {
                  $line=76;
                  if ($opEqualY(number,'6')) {
                    $line=76;
                    $result=GCollections.asList(1,1,0);
                    if (true) break $try;
                  }
                  else {
                    $line=77;
                    $result=GCollections.asList(1,1,1);
                    if (true) break $try;
                  }
                }
              }
            }
          }
        }
      }
      $line=80;
      $rethrow(new RuntimeException("The function \"\u03B41(\u27E8ba,bb,bc\u27E9:java.lang.Iterable,number:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PQ3.class,"\u03B41",$line);
    }
    return $result;
  }
  public static Object g1(java.lang.Iterable $v9) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v10=GCollections.unmodifiableCollection($v9).iterator();
      Object ba=$v10.next();
      Object bb=$v10.next();
      Object bc=$v10.next();
      $line=83;
      $result="";
      if (true) break $try;
      $line=84;
      $rethrow(new RuntimeException("The function \"g1(\u27E8ba,bb,bc\u27E9:java.lang.Iterable)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PQ3.class,"g1",$line);
    }
    return $result;
  }
  public static Object h1(java.lang.Iterable $v11, Object number) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v12=GCollections.unmodifiableCollection($v11).iterator();
      Object ba=$v12.next();
      Object bb=$v12.next();
      Object bc=$v12.next();
      $line=87;
      if ($opEqualY(number,'0')) {
        $line=88;
        if (!$opEqualY(ba,0)) {
          $line=88;
          $result='a';
          if (true) break $try;
        }
        else {
          $line=89;
          if (!$opEqualY(bb,0)) {
            $line=89;
            $result='b';
            if (true) break $try;
          }
          else {
            $line=90;
            if (!$opEqualY(bc,0)) {
              $line=90;
              $result='c';
              if (true) break $try;
            }
            else {
              $line=91;
              $result="";
              if (true) break $try;
            }
          }
        }
      }
      else {
        $line=94;
        if ($opEqualY(number,'1')) {
          $line=95;
          if (!$opEqualY(ba,0)) {
            $line=95;
            $result='a';
            if (true) break $try;
          }
          else {
            $line=96;
            if (!$opEqualY(bb,0)) {
              $line=96;
              $result='b';
              if (true) break $try;
            }
            else {
              $line=97;
              $result='c';
              if (true) break $try;
            }
          }
        }
        else {
          $line=100;
          if ($opEqualY(number,'2')) {
            $line=101;
            if (!$opEqualY(ba,0)) {
              $line=101;
              $result='a';
              if (true) break $try;
            }
            else {
              $line=102;
              if (!$opEqualY(bb,1)) {
                $line=102;
                $result='b';
                if (true) break $try;
              }
              else {
                $line=103;
                $result='c';
                if (true) break $try;
              }
            }
          }
          else {
            $line=106;
            if ($opEqualY(number,'3')) {
              $line=107;
              if (!$opEqualY(ba,0)) {
                $line=107;
                $result='a';
                if (true) break $try;
              }
              else {
                $line=108;
                if (!$opEqualY(bb,1)) {
                  $line=108;
                  $result='b';
                  if (true) break $try;
                }
                else {
                  $line=109;
                  $result='c';
                  if (true) break $try;
                }
              }
            }
            else {
              $line=112;
              if ($opEqualY(number,'4')) {
                $line=113;
                if (!$opEqualY(ba,1)) {
                  $line=113;
                  $result='a';
                  if (true) break $try;
                }
                else {
                  $line=114;
                  if (!$opEqualY(bb,0)) {
                    $line=114;
                    $result='b';
                    if (true) break $try;
                  }
                  else {
                    $line=115;
                    $result='c';
                    if (true) break $try;
                  }
                }
              }
              else {
                $line=118;
                if ($opEqualY(number,'5')) {
                  $line=119;
                  if (!$opEqualY(ba,1)) {
                    $line=119;
                    $result='a';
                    if (true) break $try;
                  }
                  else {
                    $line=120;
                    if (!$opEqualY(bb,0)) {
                      $line=120;
                      $result='b';
                      if (true) break $try;
                    }
                    else {
                      $line=121;
                      $result='c';
                      if (true) break $try;
                    }
                  }
                }
                else {
                  $line=124;
                  if ($opEqualY(number,'6')) {
                    $line=125;
                    if (!$opEqualY(ba,1)) {
                      $line=125;
                      $result='a';
                      if (true) break $try;
                    }
                    else {
                      $line=126;
                      if (!$opEqualY(bb,1)) {
                        $line=126;
                        $result='b';
                        if (true) break $try;
                      }
                      else {
                        $line=127;
                        $result='c';
                        if (true) break $try;
                      }
                    }
                  }
                  else {
                    $line=131;
                    if ($opEqualY(number,'7')) {
                      $line=132;
                      if (!$opEqualY(ba,1)) {
                        $line=132;
                        $result='a';
                        if (true) break $try;
                      }
                      else {
                        $line=133;
                        if (!$opEqualY(bb,1)) {
                          $line=133;
                          $result='b';
                          if (true) break $try;
                        }
                        else {
                          $line=134;
                          $result='c';
                          if (true) break $try;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=138;
      $rethrow(new RuntimeException("The function \"h1(\u27E8ba,bb,bc\u27E9:java.lang.Iterable,number:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PQ3.class,"h1",$line);
    }
    return $result;
  }
}
